
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-backend
    description: Backend using Spring
    author: Salim
    version: '@project.version@'
spring:
  profiles:
    active: dev